public class AccountHandler {
    public static Account insertNewAccount(String name)
    {
        try{
            Account account = new Account(Name=name,AccountNumber='AC000000');
            insert account;
            return account;
        }
        catch(DmlException e){
            System.debug('A DML exception has occurred'+ 
                            e.getMessage());
            return null;
        }
}
}